version: 2.1
jobs:
        build:
                docker: 
                        - image: circleci/ruby
                steps:
                        - bundle install
                        - bundle exec middleman build --verbose
