version: 2.1
variables:
  LANG: 'en_US.UTF-8'
  LC_ALL: 'en_US.UTF-8'
jobs:
        build:
                docker: 
                        - image: yterajima/middleman
                steps:
                        - checkout
                        - run: gem install middleman
                        - run: bundle install
                        - run: bundle exec middleman build --verbose
                        - run: bundle exec middleman s3_sync

