version: 2.1
jobs:
        build:
                docker: 
                        - image: mihcall/middleman:1.0.5
                steps:
                        - checkout
                        - run: bundle exec middleman build --verbose
                        - run: bundle exec middleman s3_sync

