version: 2.1
jobs:
        build:
                docker: 
                        - image: yterajima/middleman
                steps:
                        - checkout
                        - run: gem install middleman
                        - run: bundle install
                          #- run: bundle exec middleman build --verbose
                        - run: bundle exec middleman s3_sync

