version: 2.1
jobs:
        build:
                docker: 
                        - image: yterajima/middleman
                steps:
                        - run: gem install middleman
                        - run: bundle install
                        - run: bundle exec middleman build --verbose

