version: 2.1
jobs:
        build:
                docker: 
                        - image: baires/middleman-docker
                steps:
                        - checkout
                        - run: bundle install
                        - run: bundle exec middleman build --verbose
                        - run: bundle exec middleman s3_sync

