version: 2.1
jobs:
        build:
                docker: 
                        - image: mihcall/devconf-middleman:1.0.1
                steps:
                        - checkout
                        - run: bundle exec middleman build --verbose
                        - run: bundle exec middleman s3_sync

