version: 2.1
dependencies:
    pre:
      - bundle install
jobs:
        build:
                docker: 
                        - image: circleci/ruby
                steps:
                        - bundle exec middleman build --verbose
