version: 2.1
jobs:
        build:
                docker: 
                        - image: yterajima/middleman
                steps:
                        - run: bundle exec middleman build --verbose
