version: 2.1
jobs:
        build:
                docker: 
                        - image: ruby:2.6.3
                steps:
                        - checkout
                        - run: gem install middleman
                        - run: bundle install
                        - run: bundle exec middleman build --verbose
                        - run: bundle exec middleman s3_sync

